coverage:
  range: "0...40"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default

status:
    project:                   # measuring the overall project coverage
      break:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: 30%
        threshold: null
        branches: null           # specify the target coverage for each commit status
        base: auto

    patch:                     # pull requests only: this commit status will measure the                       # adjusted are covered at least X%.
      break:
        enabled: yes             # must be yes|true to enable this status
        target: 30%              # specify the target "X%" coverage to hit
        threshold: null
        branches: null           # specify the target coverage for each commit status
        base: auto

ignore:
    - app/src/main/java/com/mdsgpp/cidadedemocratica/External/*
    - app/src/main/java/com/mdsgpp/cidadedemocratica/controller/*
    - app/src/main/java/com/mdsgpp/cidadedemocratica/view/*
    - app/src/main/java/com/mdsgpp/cidadedemocratica/push/*
